### PR TITLE
Merge and adapt changes from trunk (MiMo/MMTabBarView)

### PR DESCRIPTION
**Pull request by TAKeanice**
Solved all conflicts.
Adapted Sierra style to use asset catalogs.
Also I ditched the 10.10 requirement, since in my testing, there were no issues whatsoever keeping MMTabBar 10.9 compatible, even with the Mojave style and without @available checks.

### CODE REVIEW

**Comment by barijaona** [comment]
@josh64x2 I made a [constantAvailability branch](https://github.com/barijaona/MMTabBarView/tree/constantAvailability), but I remain undecided…

**Comment by TAKeanice** [comment]
This was actually not done due to conflicts, but because the @available check was unnecessary given that both branches contained the exact same code. Did I see something wrong here?

**Comment by barijaona** [comment]
I see some differences.
Compare for instance https://github.com/TAKeanice/MMTabBarView/blob/merge_trunc/MMTabBarView/MMTabBarView/Styles/Mojave%20Tab%20Style/MMMojaveTabStyle.m#L54-L57

and 

https://github.com/MiMo42/MMTabBarView/blob/master/MMTabBarView/MMTabBarView/Styles/Mojave%20Tab%20Style/MMMojaveTabStyle.m#L54-L64

**Comment by TAKeanice** [comment]
I meant in the two branches of the @available statement. In both cases in your example it is `return NSMakeSize(NSViewNoIntrinsicMetric, 26);`

**Comment by barijaona** [comment]
There is a subtle difference.
Apple fixed a typo 😆  : we should now use NSViewNoIntrinsicMetric instead of NSViewNoIn**s**trinsicMetric (note the extra s)

**Comment by TAKeanice** [comment]
Are you kidding me? :D Alright, I will change it back straight away. Probably that was meant when the original PR author for the Mojave style wrote about „modern” APIs...

**Comment by TAKeanice** [comment]
I changed it back in every place, where `NSViewNoIntrinsicMetric` was used, with a quick´n´dirty c function that gives me the value back, depending on the OS version. I think it is not a pretty solution, so I am open for suggestions @barijaona ... And maybe you can tell me why xCode does not complain when compiling for 10.9. Was the api change backported somehow?

**Comment by barijaona** [comment]
As discussed in #3, Apple marked NSViewNoIn**s**trinsicMetric as deprecated, but maintained it. My version of Xcode does not emit warnings about it.

My personal opinion is that Apple will keep it that way for many years. It would be irresponsible from them not to assume the consequences of a typo that has affected 11 versions of OS X… 

So I came to the conclusion that we should continue using NSViewNoIn**s**trinsicMetric, at least until Xcode begins to explicitly warn us… But, seeing @balthisar using `@available`, I came to wonder if we should respect his choice, at least for the parts he wrote…

**Comment by barijaona** [comment]
As explained in latest comment at https://github.com/MiMo42/MMTabBarView/pull/62, a few lines of MMMojaveTabStyle+Assets.m are 10.9 incompatible.

**Comment by TAKeanice** [comment]
But it does compile with target 10.9 though... Why is that? I am really confused about this whole incompatibility. Is it ok to build for 10.9 and use Sierra style in 10.9-10.13, and Mojave from 10.14 onwards?

**Comment by josh64x2** [comment]
@takeanice that would be my preference:)

**Comment by barijaona** [comment]
I’ll try to make Sierra style compatible with dark mode on Mojave

**Comment by TAKeanice** [comment]
Why that @barijaona ? Mojave style is compatible. So if we use it in 10.14 onwards, there will be no issue!

**Comment by barijaona** [comment]
Sorry, I was offline during most of the week-end.

I don't know why Xcode does not systematically complain when the user targets 10.9 while using constants available from 10.10 onward, but NSViewNoIntrinsicMetric is not the only case I noticed. We should probably file radars for these.

I agree that regarding Vienna, we could use Mojave style for 10.14+ and keep Sierra style for 10.9 to 10.13, but improving Sierra might be worth it: 
1/ @josh64x2 wrote he is not thrilled by the look of Mojave style
2/ Sierra style resizes tabs to fit the available width, while Mojave style does not
2/ While Xcode does not complain, Mojave is not currently compatible with 10.9 (sorry for the confusion I caused). Therefore, I am a bit reluctant to tag the current state of Vienna's MMTabBarView repo as OK.

I have pushed a `DarkSierra` branch in my repo. It is not finished yet (it does not dynamically adapts when the user switches between dark and clear modes), but your first feedbacks are welcome.

**Comment by josh64x2** [comment]
@barijaona I'm actually only concerned with the font, which I think would be easy to work around. I'm not worried about the tabs not filling the available width - in fact I think I prefer that they don't fill the full width.

My preference is to use the Mojave style on 10.14, and the Sierra style on everything else.
I think we should try and keep as close to Vanilla MMTabBarView - essentially outsource the development to that team and that will free up time to work on the parts of Vienna that we need to really fix.

**Comment by barijaona** [comment]
May be we should separate better the discussion around a solution for Vienna (which might be [#1189](https://github.com/ViennaRSS/vienna-rss/pull/1189)) and the current issue (#7), which should mainly center on MMTabBarView itself.

Technically, I am not very satisfied with this #7 : MMTabBarView claims to be 10.9 compatible, while it is not, due to the two occurrences of `[NSColor labelColor]`. We need to have a fix for this.

Regarding Vienna's #1189, it's mostly a question of taste. I'll  continue the discussion there.

**Comment by TAKeanice** [comment]
If runtime errors are the only issue in 10.9 compatibility, the two occurrences of `[NSColor labelColor]` pose no problem, since they can be circumvented with `@available` checks. Or even, since a custom asset catalog is used for Mojave style, be replaced with self-defined colors.

I think having many available styles in MMTabBar does no harm, as it makes it more versatile for various apps. They also do not add much to the size. Making Sierras style dark-mode compatible is a good idea from that perspective: Then there is one more style to use for users of MMTabBar, which stays good for Mojave.

**Comment by TAKeanice** [comment]
Someone already proposed the `@available` solution on the main MMTabBar repo: https://github.com/MiMo42/MMTabBarView/pull/64. I will integrate the changes into this branch.

**Pull request merged**
