### PR TITLE
Add missing header to SPM public header and insert NSBundle macro

### PR DESCRIPTION
**Pull request by Eitot**
Swift Package Manager puts image resources into a separate bundle within the Resources directory. It also provides this macro as a shorthand to retrieve the correct NSBundle instance.

### CODE REVIEW

**Comment by Eitot** [comment]
This is not working entirely yet. The images appear and sometimes disappear. I noticed that even the non-SPM version has some problems since my last PRs. MMTabBarView uses macros extensively for the images, so I am beginning to wonder that the project reorganisation broke something. Moreover, the NSImage calls may not use the correct NSBundle to retrieve the images.

**Comment by barijaona** [comment]
I get a strange error on MMTabBarView/MMTabBarView/MMTabDragWindow.h , line 10 :
https://github.com/Eitot/MMTabBarView/blob/e707144a851e04243d5eacc083e473c66be790fd/MMTabBarView/MMTabBarView/NSCell%2BMMTabBarViewExtensions.h#L10

> Cocoa is not available when building for iOS. Consider using `#if !TARGET_OS_IOS` to conditionally import this framework, first importing TargetConditionals.h if necessary.

**Review by barijaona — CHANGES_REQUESTED** [review]
I get a strange error on MMTabBarView/MMTabBarView/MMTabDragWindow.h , line 10 :
https://github.com/Eitot/MMTabBarView/blob/e707144a851e04243d5eacc083e473c66be790fd/MMTabBarView/MMTabBarView/NSCell%2BMMTabBarViewExtensions.h#L10

> Cocoa is not available when building for iOS. Consider using `#if !TARGET_OS_IOS` to conditionally import this framework, first importing TargetConditionals.h if necessary.

**Comment by Eitot** [comment]
I cannot reproduce this. Perhaps this can be fixed by specifying a platform.

**Review by barijaona — CHANGES_REQUESTED** [review]
No success: 

in MMTabBarView/MMTabBarView/MMTabDragWindow.h, line 10, the error has changed and is now:
>Module 'Cocoa' not found

in MMTabBarView/MMTabBarView/MMTabDragWindowController.h:10:9, line 10, a new occurence of:
> Cocoa is not available when building for iOS. Consider using `#if !TARGET_OS_IOS` to conditionally import this framework, first importing TargetConditionals.h if necessary.

https://github.com/Eitot/MMTabBarView/blob/3a574dd8453e026e890db3a57b257f0883ac081a/MMTabBarView/MMTabBarView/MMTabDragWindow.h#L10

**Comment by Eitot** [comment]
Where are you seeing these? Which project are you building?

**Comment by barijaona** [comment]
Ooooups !!! I didn't notice that my build target had changed, for whatever reason…

**Review by barijaona — APPROVED** [review]

**Pull request merged**
